---

- name: Manage SSH public keys
  hosts: [ 'debops_all_hosts', 'debops_service_authorized_keys' ]
  become: True

  roles:

    - role: debops.authorized_keys
      tags: [ 'role::authorized_keys' ]
